= Spring Cloud Bootstrapping



== Building from source
Can be easily built with the
https://github.com/takari/maven-wrapper[maven wrapper]. You also need JDK 10.

[indent=0]
----
	$ ./mvnw clean package --update-snapshots
----

If you want to build with the regular `mvn` command, you will need
https://maven.apache.org/run-maven/index.html[Maven v3.5.0 or above].

NOTE: You may need to increase the amount of memory available to Maven by setting
a `MAVEN_OPTS` environment variable with the value `-Xmx512m`. Remember
to set the corresponding property in your IDE as well if you are building and running
tests there (e.g. in Eclipse go to `Preferences->Java->Installed JREs` and edit the
JRE definition so that all processes are launched with those arguments). This property
is automatically set if you use the maven wrapper.


== Starting on Docker container
You also need Docker Compose.

[indent=0]
----
	$ sudo docker-compose build --force-rm
	$ sudo docker-compose up configuration
	$ sudo docker-compose up discovery
	$ sudo docker-compose up gateway
	$ sudo docker-compose up provider
	$ sudo docker-compose up consumer
----

http://localhost:8081[Configuration exposed on port 8081].

http://localhost:8082[Discovery exposed on port 8082].

http://localhost:8080[Gateway exposed on port 8080].

http://localhost:8083[Provider exposed on port 8083].

http://localhost:8084[Consumer exposed on port 8084].

NOTE: Some settings can be changed in the `.env` file.

You may want to automate the https://docs.docker.com/compose/startup-order/[order of startup and shutdown of containers].



== Making requests
You alse need cURL.


=== Request to provider

[indent=0]
----
	$ curl -X GET http://localhost:8080/provider/greetings
----


=== Request to consumer
----
	$ curl -X GET http://localhost:8080/consumer/greetings
or
	$ curl -X GET http://localhost:8080/consumer/greetings?name=Foo
----

NOTE: Check instances currently registered on http://localhost:8082.



== Modules
There are a number of modules in Spring Cloud Bootstrapping, here is a quick overview:


=== spring-cloud-bootstrapping-configuration
https://github.com/kinlhp/spring-cloud-bootstrapping/tree/master/spring-cloud-bootstrapping-project/spring-cloud-bootstrapping-configuration[Configuration server].


=== spring-cloud-bootstrapping-discovery
https://github.com/kinlhp/spring-cloud-bootstrapping/tree/master/spring-cloud-bootstrapping-project/spring-cloud-bootstrapping-discovery[Discovery server].


=== spring-cloud-bootstrapping-gateway
https://github.com/kinlhp/spring-cloud-bootstrapping/tree/master/spring-cloud-bootstrapping-project/spring-cloud-bootstrapping-gateway[Gateway server].


=== spring-cloud-bootstrapping-provider
https://github.com/kinlhp/spring-cloud-bootstrapping/tree/master/spring-cloud-bootstrapping-project/spring-cloud-bootstrapping-provider[Service provider].


=== spring-cloud-bootstrapping-consumer
https://github.com/kinlhp/spring-cloud-bootstrapping/tree/master/spring-cloud-bootstrapping-project/spring-cloud-bootstrapping-consumer[Service consumer].



= References
- https://www.baeldung.com/spring-cloud-bootstrapping[Baeldung].
- http://www.matera.com/blog/post/desenvolvendo-microsservicos-spring-cloud-netflix[Blog Matera].
- https://docs.docker.com/[Docker].
- https://docs.docker.com/[Docker Compose].
- https://github.com/spring-projects/spring-boot[Spring Boot].
